// Command genstatic builds the read-only copy of the UI that is published to
// GitHub Pages.
//
// Pages only serves static files, so there is no /api/spec to fetch: the spec
// is baked into a small script instead, and the UI starts in browse-only mode
// until the visitor points it at a locally running intralens.
//
// Usage:
//
//	go run ./cmd/genstatic --out dist
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	intralens "github.com/keusidan/intralens"
	"github.com/keusidan/intralens/internal/spec"
)

const specScript = `assets/js/spec.data.js`

func main() {
	out := flag.String("out", "dist", "output directory")
	flag.Parse()

	if err := build(*out); err != nil {
		fmt.Fprintln(os.Stderr, "genstatic:", err)
		os.Exit(1)
	}
}

func build(out string) error {
	document, err := spec.Load()
	if err != nil {
		return err
	}

	web, err := fs.Sub(intralens.WebFS, "web")
	if err != nil {
		return err
	}

	if err := os.RemoveAll(out); err != nil {
		return fmt.Errorf("clean %s: %w", out, err)
	}

	count := 0
	err = fs.WalkDir(web, ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return os.MkdirAll(filepath.Join(out, path), 0o755)
		}

		data, err := fs.ReadFile(web, path)
		if err != nil {
			return err
		}
		if path == "index.html" {
			data = injectSpecScript(data)
		}
		count++
		return os.WriteFile(filepath.Join(out, path), data, 0o644)
	})
	if err != nil {
		return err
	}

	payload, err := specPayload(document)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(out, specScript), payload, 0o644); err != nil {
		return err
	}

	// Pages would otherwise run the files through Jekyll, which drops
	// directories starting with an underscore.
	if err := os.WriteFile(filepath.Join(out, ".nojekyll"), nil, 0o644); err != nil {
		return err
	}

	fmt.Printf("wrote %s: %d files + the embedded spec (%d operations)\n", out, count, len(document.Operations))
	return nil
}

// injectSpecScript loads the baked spec before the application scripts.
func injectSpecScript(page []byte) []byte {
	marker := `<script src="assets/js/api.js"></script>`
	replacement := `<script src="` + specScript + `"></script>` + "\n" + marker
	return []byte(strings.Replace(string(page), marker, replacement, 1))
}

func specPayload(document *spec.Document) ([]byte, error) {
	var pretty json.RawMessage = document.JSON
	encoded, err := json.Marshal(pretty)
	if err != nil {
		return nil, err
	}
	// `</script>` inside the literal would close the host tag early.
	safe := strings.ReplaceAll(string(encoded), "</", `<\/`)

	return []byte("/* Generated by cmd/genstatic -- the OpenAPI document, for the static build. */\n" +
		"window.INTRALENS_SPEC = " + safe + ";\n"), nil
}
